# Generated by Django 5.2.4 on 2026-04-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
