# Generated by Django 5.2.4 on 2026-04-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free_shipping_eligible',
            field=models.BooleanField(default=False, help_text='If True, qualifies for free shipping at order threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=800, help_text='Shipping cost for this product', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Tax percentage for this product (e.g., 5, 8, 12)', max_digits=5),
        ),
    ]
