# Generated by Django 5.2.4 on 2026-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_is_free_shipping_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_free_shipping_eligible',
            field=models.BooleanField(default=True, help_text='If True, this product qualifies for free shipping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost in rupees. Set 0 for free shipping, or custom amount', max_digits=10),
        ),
    ]
