# Generated by Django 5.2.4 on 2026-04-20 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_order_address_remove_order_apartment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax and shipping', max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, help_text='Shipping amount', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, help_text='Tax amount', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=10)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('other', 'Other')], default='razorpay', max_length=20)),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(db_index=True, max_length=100)),
                ('razorpay_signature', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='api_payment_razorpa_7700f3_idx'), models.Index(fields=['razorpay_payment_id'], name='api_payment_razorpa_4d38fa_idx'), models.Index(fields=['user', 'transaction_date'], name='api_payment_user_id_9b26ad_idx')],
            },
        ),
    ]
