# Generated by Django 5.2.4 on 2026-04-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_url',
            field=models.CharField(blank=True, default='', help_text='URL to product details page', max_length=500),
        ),
    ]
