# Generated by Django 5.2.4 on 2026-04-21 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_paymenttransaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.OneToOneField(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='api.order'),
            preserve_default=False,
        ),
    ]
