# Generated by Django 5.2.4 on 2026-04-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_paymenttransaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_the_way', 'On the Way'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='api.order'),
            preserve_default=False,
        ),
    ]
