# Generated by Django 5.2.4 on 2026-05-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_shipping_min_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower value = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('is_fallback', models.BooleanField(default=False, help_text='Used when no pincode prefix rule matches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZonePinPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_prefixes', to='api.shippingzone')),
            ],
            options={
                'ordering': ['prefix'],
            },
        ),
    ]
